name: Demo
on:
  pull_request:
    types:
      - closed
      - opened
    branches:
      - master
      - dev
      - feature/*
      - bugfix/*
      - hotfix/*
      - release/*
  workflow_dispatch:
  push:
    branches:
      - master
      - dev
      - feature/*
      - bugfix/*
      - hotfix/*
      - release/*
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '**.yaml'
      - '**.json'
  schedule:
    - cron: '0 0 * * *'
jobs:
  start-project:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Dependencies
        run: npm ci --force
      - name: Start project
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Playwright
        run: npx playwright install --with-deps
      - name: Wait for localhost
        run: |
          npm run start &
          until $(curl --output /dev/null --silent --head --fail http://localhost:4200); do
            echo "Waiting for localhost to be available..."
            sleep 5
          done
      # - name: Run project
      #   run: percy exec -- npx npm run start


      - name: Run tests
        run: npm run projectTest
  build:
    needs: start-project
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci --force
      - name: Build website
        run: npm run lambdaTest




